name: Retrieve Media Prima Dailymotion HLS manifest with token

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0/24 * * *'
    
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
     
      
      - name: Main
        env: 
         AUTH: ${{ secrets.AUTH }} 

        run: |
          pwd
          chmod +x download_token.sh
          ./download_token.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: config
        run: |
          git config --global user.email malaysiafx2@gmail.com
          git config --global user.name AqFad2811
          git add .
          git commit -m "Update new token" 
      
      - name: commit
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: main
